## commands to run jobs

## parameters

## genome references
references_dir:  '/hps/nobackup/stegle/datasets/references/human/GRCh37/'
human_gx_fasta: '/nfs/leia/research/stegle/dseaton/genomes/hg19/fasta/GRCh37.p13.genome.full.fa'
sample_metadata_file: '/nfs/leia/research/stegle/dseaton/hipsci/singlecell_neuroseq/data/metadata/sample_tracking.tsv'
pool_metadata_file: '/nfs/leia/research/stegle/dseaton/hipsci/singlecell_neuroseq/data/metadata/pool_tracking.tsv'


#human_gx_fasta: '/hps/nobackup/stegle/datasets/references/human/GRCh37.p13.genome.full.fa'
#human_tx_fasta:  'Homo_sapiens.GRCh37.rel75.cdna.all.ERCC92.fa.gz'
#human_fasta_unzipped:  'Homo_sapiens.GRCh37.rel75.cdna.all.fa'
#kallisto_idx:  'Homo_sapiens.GRCh37.rel75.cdna.all.ERCC92.kallisto_v0.43_idx'

## data


